### ISSUE TITLE
Create a dockerfile that dockerises removing_subscribers

### ISSUE THREAD

**Issue by gem09lo** [gem09lo/PriceSlashTrack#79]
# Description
Create a dockerfile that dockerises the process of cleaning data from unsubscribed products so that it can be hosted on the cloud and triggered automatically every 24 hours

# Outcome
- Create a dockerfile script that copies over the `remove_subscribers.py` as well as all the relevant files i.e. `requirements.txt` etc, ready to be pushed to an ECR repo

# User Story
As an engineer, I want to automate the data cleaning process for unsubscribed products, so that it can run seamlessly on the cloud every 24 hours.

**Comment by jk-george** [comment]
## Additions to this ticket:

Creating a dockerfile for the dashboard for when it is ready to be hosted on the cloud. Update the terraform scripts so that it reflects this change.


### User Story:

As an engineer at Price Slashers, I want to be able to utilise the cloud to run the dashboard.
