### ISSUE TITLE
Dockerising streamlit script + Adding bash scripts for easier deployment.

### ISSUE THREAD

**Issue by gem09lo** [gem09lo/PriceSlashTrack#82]
# Description
Create a dockerfile that dockerises the streamlit dashboard so that it can be hosted on the cloud and accessed by users.

# Outcome
Create a dockerfile script that copies over the streamlit python script as well as all the relevant files i.e. requirements.txt etc, ready to be pushed to an ECR repo.

**Comment by jk-george** [comment]
## Context:

- This step has already been done.
- Going to use this Issue to move dockerfile and requirements into the dashboard folder
