### ISSUE TITLE
Add homepage to streamlit dashboard

### ISSUE THREAD

**Issue by gem09lo** [gem09lo/PriceSlashTrack#84]
# Description
There will be a section on the homepage that informs users on how to use the dashboard.

# Outcome
- Add an "About" section on the homepage which will explain to the users what the dashboard is, how it works and any relevant information.

# User Story
As a new customer, I want to be able to login to the dashboard using my credentials and see information about the dashboard, so I know how to subscribe and track products and know the basic functionality of the dashboard.

**Comment by indiah444** [comment]
Apologies, didn't see that you'd already written a ticket for this! I've written another one for this and linked it to a PR I just made.
